### ISSUE TITLE
some images fail to process

### ISSUE THREAD

**Issue by ManoaNosea** [minyuanye/SIUN#4]
```
Traceback (most recent call last):
  File "deblur.py", line 53, in <module>
    Application(config).start()
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\SIUN-master\code\src\application.py", line 23, in start
    self.application()
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\SIUN-master\code\src\application.py", line 109, in application
    deblurs = self.__deblur(imageBlur,imageOrigin)
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\SIUN-master\code\src\application.py", line 76, in __deblur
    batch_gen = self.model.generator.predict(data_X)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\keras\engine\training.py", line 1380, in predict
    x, _, _ = self._standardize_user_data(x)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\keras\engine\training.py", line 757, in _standardize_user_data
    exception_prefix='input')
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\keras\engine\training_utils.py", line 141, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected imageSmall to have shape (None, None, 6) but got array with shape (128, 128, 8)
```

**Comment by minyuanye** [comment]
Input images should only contain RGB 3 channels. It seems that your input images contain RGBA 4 channels.

**Comment by bixiwen** [comment]
I have the same problem

**Comment by Johnreidsilver** [comment]
PNG's will have alpha channel, even in GIMP saving without the alpha channel seems to generate a 4 channel image in PNG.

To load only 3 channels in application.py add imageBlur=imageBlur[:,:,:3] in __getImage after imageBlur
