### ISSUE TITLE
Error while running the coda

### ISSUE THREAD

**Issue by freedom9393** [minyuanye/SIUN#5]
I installed everything inside requirements.txt but got following error:

```
Traceback (most recent call last):
  File "C:\Users\siroj\Anaconda3\envs\siun\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\Users\siroj\Anaconda3\envs\siun\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deblur.py", line 39, in <module>
    set_session_config(per_process_gpu_memory_fraction=1, allow_growth=True, device_list=args.gpu)
  File "E:\Sherzod\Projects\SIUN\code\src\lib\tf_util.py", line 10, in set_session_config
    import tensorflow as tf
  File "C:\Users\siroj\Anaconda3\envs\siun\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\siroj\Anaconda3\envs\siun\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\siroj\Anaconda3\envs\siun\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\siroj\Anaconda3\envs\siun\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_80.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 8.0 from this URL: https://developer.nvidia.com/cuda-toolkit
```

What does this error mean?

**Comment by TrinhQuocNguyen** [comment]
Hi @freedom9393 
Can you try these package instead?
# pip3 install -r requirements.txt
h5py==2.7.1
tensorflow-gpu==1.15.0
Keras==2.2.4
scikit-image==0.14.3
Have a nice day.

**Comment by mardukbp** [comment]
@freedom9393 That means that it expects CUDA 8.0 to be installed. Did you install it?

**Comment by freedom9393** [comment]
@mardukbp Yes, thanks 👍

**Comment by mardukbp** [comment]
1. See if that DLL is present in the CUDA bin directory (maybe `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin`). It could have a different name. In that case open cmd.exe as Administrator and create a symlink: `mklink cudart64_80.dll original_file.dll`.
2. Verify that this directory is in your PATH. In the Anaconda Terminal enter `echo %PATH%`
